### ISSUE TITLE
I upgraded from 1.7.4.4 to 1.7.4.11 and get 'Factory is not initialized with NetOffice assemblies.' exception

### ISSUE THREAD

**Issue by ErikDeRoos** [netoffice/NetOffice#15]
I use the Powerpoint package for a long time now, around 5 years. It is a great product, thanks!

I upgraded from 1.7.4.4 (it says 1.7.3.0 somewhere else) to 1.7.4.11 and now I get the 'Factory is not initialized with NetOffice assemblies.' exception.
I can open a Powerpoint file but when I try to access Slides.First() it comes with this exception.
All dll's are alongside my executable.

This is how the Factory in the application object looks like:
![afbeelding](https://user-images.githubusercontent.com/17176362/103318184-e15ec400-4a2d-11eb-8b36-90f2ab6d9f54.png)

This is the project I am using your product in: https://github.com/ErikDeRoos/koningskerk-beamteam

**Comment by beshel** [comment]
I experienced the same updating my Excel libs via nuget.

**Comment by itsho** [comment]
https://github.com/NetOfficeFw/NetOffice/issues/276

**Comment by ErikDeRoos** [comment]
> 
> 
> [NetOfficeFw/NetOffice#276](https://github.com/NetOfficeFw/NetOffice/issues/276)

This is the fix.
