### ISSUE TITLE
Obtaining an older version of NetOffice, is it possible?

### ISSUE THREAD

**Issue by lboening** [netoffice/NetOffice#17]
I am looking for NetOffice of a particular vintage.

'OfficeApi, Version=1.5.1.2, Culture=neutral, PublicKeyToken=a39beb0835c43c8e'

Where might I find it?

**Comment by erikaleblanc88** [comment]
@lboening I keep a private history repository with the old binaries that were committed to source control before the nuGet packages became a thing and here is what I have:

- [OfficeApi.1.5.1.2.zip](https://github.com/netoffice/NetOffice/files/6519576/OfficeApi.1.5.1.2.zip)

![image](https://user-images.githubusercontent.com/39452098/119070899-33918900-b9bf-11eb-9d9e-30be26e078cb.png)

Hope that helps! :gem:

**Comment by lboening** [comment]
Thanks. That's what I needed. It turns out it could be another problem.
