### ISSUE TITLE
NetOffice organization ownership takeower

### ISSUE THREAD

**Issue by jozefizso** [netoffice/NetOffice#3]
> Note: NetOffice project moved to https://github.com/NetOfficeFw

Hi @caioproiete,
I would like to take ownership of the [netoffice](https://github.com/netoffice) organization on GitHub.

Sebastian made me a coordinator on the existing [NetOffice project on Codeplex](https://netoffice.codeplex.com/) to help him with project migration to GitHub. Codeplex portal will shutdown this year. Sebastian also [announced](https://netofficedotnet.wordpress.com/2017/06/03/this-is-the-end/) he will end his work on NetOffice project by the end of year 2017.

The NetOffice organization and repository  feels a bit lonely and outdated. I would like to change it and make the NetOffice project alive again.

### My plans with NetOffice project
* release new source code in git when Sebastian makes it available,
* make NetOffice organization the center of development for NetOffice projects,
* make it easier for users to get the library,
* host NetOffice documentation,
* improve NetOffice code generation and build system,
* make contributions to source code more approachable.

As Codeplex will shutdown later this year, I would like to unify NetOffice projects, which are on different places now, and keep everything under https://github.com/netoffice/

To make this possible, I need the Owner rights on NetOffice organization so I can manage all aspects of projects and related stuff.

**Comment by caioproiete** [comment]
@jozefizso Let's schedule a Skype call to discuss the roadmap for NetOffice. I'm happy to have you as co-owner of the NetOffice organization and we can definitely work together on supporting NetOffice and moving it forward.

**Comment by jozefizso** [comment]
Reopening the issue as it was not solved yet :)

**Comment by jozefizso** [comment]
pinging @caioproiete...

**Comment by jozefizso** [comment]
As @caioproiete stopped communicating with me and Sebastian and he his not willing to maintain the NetOffice organization, we are moving the project to the new location at https://github.com/NetOfficeFw
