### ISSUE TITLE
New code

### ISSUE THREAD

**Issue by abrenner85** [netoffice/NetOffice#7]
Hallo,
we use NetOffice in our enterprise app. Do you still develop the library? This code looks a bit old.

Thanks,
Alda

**Comment by maliutin** [comment]
Hi.

You can look at another repository https://github.com/NetOfficeFw

**Comment by caioproiete** [comment]
@abrenner85 Yes, we're working on the next release.

**Comment by abrenner85** [comment]
WHere can I get the new code please?

**Comment by caioproiete** [comment]
@abrenner85 Subscribe to this repository to be notified of new releases.

![image](https://user-images.githubusercontent.com/177608/38617193-b31b80cc-3d6c-11e8-9acd-c78ae446c857.png)
