### ISSUE TITLE
NetOffice 1.7.4.1 how to register library dll in office (outlook) 2016?

### ISSUE THREAD

**Issue by arkadiuszGolec** [netoffice/NetOffice#9]
I have some project witch add some features to outlook. My project includs dll-s like (Netoffice, OfficeApi, OutlookApi). 

I registered dll using vbs script like this:
Dim WshShell
Set WshShell = CreateObject("Wscript.Shell")
WshShell.run "c:\Windows\Microsoft.NET\Framework\v4.0.30319\regasm KLO.Addins.Outlook.NetOffice.dll"
Set WshShell = nothing

And I cant see my  addins in extensions in outlook 2016.

This project works fine in office 2007, 2010 and 2013.

can you help with this issue?

Best regards

**Comment by caioproiete** [comment]
Hi @arkadiuszGolec, this issue tracker is for bugs/features, etc. for general questions I suggest you try [StackOverflow](https://stackoverflow.com/questions/tagged/netoffice).
